
set VSHADOW=vshadow.exe
set SHADOWSCRIPT=vss-setvar.cmd
set LN=ln.exe
for /f "delims=" %%a in ('%LN% --datetime') do set SHARE=%%a
set SHARE="20130504"

REM create a persistent shadow
REM
%VSHADOW% -script=%SHADOWSCRIPT% -p e:

REM vss-setvar.cmd is generated by vshadow.exe
REM
call %SHADOWSCRIPT%

%VSHADOW% -er=%shadow_id_1%,"%SHARE%",tmp

pause 
REM delete the shadow
REM
%VSHADOW% -ds=%shadow_id_1%
