@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {cf1608cd-d438-416b-b56f-1f88de897665}]
@echo.

SET SHADOW_SET_ID={cf1608cd-d438-416b-b56f-1f88de897665}
SET SHADOW_ID_1={e5c94905-2e64-4d42-9b59-4b49c5cae58f}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy5
