#define STR_VALUE(arg)    #arg
#define STR_NAME(name)    STR_VALUE(name)

#define MAJOR_VERSION_STRING			STR_NAME(MAJOR_VERSION)
#define MINOR_VERSION_STRING			STR_NAME(MINOR_VERSION)
#define PATCH_VERSION_STRING			STR_NAME(PATCH_VERSION)
#define HOTFIX_VERSION_STRING			STR_NAME(HOTFIX_VERSION)
#define VERSION_DOT "."

#define VERSION_STRING MAJOR_VERSION_STRING VERSION_DOT MINOR_VERSION_STRING VERSION_DOT PATCH_VERSION_STRING VERSION_DOT HOTFIX_VERSION_STRING
#define VERSION_NUMBER MAJOR_VERSION_STRING VERSION_DOT MINOR_VERSION_STRING PATCH_VERSION_STRING HOTFIX_VERSION_STRING
