REM
REM Preparation for nested junctions
REM

@echo off
set TESTROOT=%1
set TESTROOTSRC=%TESTROOT%%DEEPPATH%\source
set TESTROOTDST=%TESTROOT%%DEEPPATH%\dest
set TESTROOTBKP=%TESTROOT%%DEEPPATH%\bk1

set OPTION_PREP=%2

if [%3] == [] ( 
  set OPTION_PREP=--%2
) else (
  set OPTION_PREP=--%2 --%3
)


REM
REM The advanced case of hidden reparse points
REM
%MKDIR% %TESTROOTSRC%\X_F0 > nul
%MKDIR% %TESTROOTSRC%\I_F1 > nul
%MKDIR% %TESTROOTSRC%\I_F1\B_F1_F0 > nul
%MKDIR% %TESTROOTSRC%\D_F2 > nul
%MKDIR% %TESTROOTSRC%\D_F2\A_F2_F0 > nul

%LN% %OPTION_PREP% %TESTROOTSRC%\X_F0 %TESTROOTSRC%\Z_J0 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\I_F1\B_F1_F0 %TESTROOTSRC%\X_F0\C_F0_J0 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\D_F2 %TESTROOTSRC%\I_F1\B_F1_F0\A_F1_F0_J0 > nul

%LN% %OPTION_PREP% %TESTROOTSRC%\Z_J0\C_F0_J0 %TESTROOTSRC%\V_J1 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\Z_J0\C_F0_J0\A_F1_F0_J0 %TESTROOTSRC%\M_J2 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\Z_J0\C_F0_J0\A_F1_F0_J0\A_F2_F0 %TESTROOTSRC%\G_J3 > nul

%LN% %OPTION_PREP% %TESTROOTSRC%\Z_J0\C_F0_J0\A_F1_F0_J0\A_F2_F0 %TESTROOTSRC%\A_J4 > nul
