REM
REM Preparation for Unroll test
REM

@echo off
set TESTROOT=%1
set TESTROOTSRC=%TESTROOT%%DEEPPATH%\source
set TESTROOTDST=%TESTROOT%%DEEPPATH%\dest
set TESTROOTBKP=%TESTROOT%%DEEPPATH%\bk1

set OPTION_PREP=%2

if [%3] == [] ( 
  set OPTION_PREP=--%2
) else (
  set OPTION_PREP=--%2 --%3
)

@%RD% %TESTROOT% 

REM F0
%MKDIR% %TESTROOTSRC%\F0 > nul
%COPY% test\ln.h %TESTROOTSRC%\F0\F0.txt > nul

%MKDIR% %TESTROOTSRC%\F0\F0_F1 > nul
%COPY% test\ln.h %TESTROOTSRC%\F0\F0_F1\F0_F1.txt > nul

%MKDIR% %TESTROOTSRC%\F0\F0_F1\F0_F1_F0 > nul
%MKDIR% %TESTROOTSRC%\F0\F0_F1\F0_F1_F1 > nul
%COPY% test\ln.h %TESTROOTSRC%\F0\F0_F1\F0_F1_F1\F0_F1_F1.txt > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\F0\F0_F1\F0_F1_F1 %TESTROOTSRC%\F0\F0_F1\F0_F1_J2 > nul

REM F1
%MKDIR% %TESTROOTSRC%\F1 > nul
%COPY% test\ln.h %TESTROOTSRC%\F1\F1.txt > nul

%MKDIR% %TESTROOTSRC%\F1\F1_F0 > nul
%COPY% test\ln.h %TESTROOTSRC%\F1\F1_F0\F1_F0.txt > nul

%LN% %OPTION_PREP% %TESTROOTSRC%\F0\F0_F1 %TESTROOTSRC%\F1\F1_F0\F1_F0_J0 > nul

REM F2
%MKDIR% %TESTROOTSRC%\F2 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\F1 %TESTROOTSRC%\F2\F2_J0 > nul

REM F3
%MKDIR% %TESTROOTSRC%\F3 > nul
%LN% %OPTION_PREP% %TESTROOTSRC%\F2 %TESTROOTSRC%\F3\F3_J0 > nul


@if [%2] == [symbolic] ( 
  %LN% %OPTION_PREP% %TESTROOTSRC%\F0\F0_F1\F0_F1_F1\F0_F1_F1.txt %TESTROOTSRC%\F0\F0_F1\F0_F1_F0\F0_F1_F0.syl > nul
  %LN% %OPTION_PREP% %TESTROOTSRC%\F0\F0_F1\F0_F1.txt %TESTROOTSRC%\F1\F1_F0\F1_F0.syl > nul
) 

REM F4
%LN% %OPTION_PREP% %TESTROOTSRC%\F0 %TESTROOTSRC%\J4 > nul

@echo on
@echo.
@REM %WHERE% *.* %TESTROOTSRC% | sort

