@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {6e88f552-7f4a-45c0-aeb9-b7a23235e4a6}]
@echo.

SET SHADOW_SET_ID={6e88f552-7f4a-45c0-aeb9-b7a23235e4a6}
SET SHADOW_ID_1={27a815a9-7319-4a00-87d1-0296023b0d09}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy12
