@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {45256b09-6891-48da-bcc8-fe8abe8e60cf}]
@echo.

SET SHADOW_SET_ID={45256b09-6891-48da-bcc8-fe8abe8e60cf}
SET SHADOW_ID_1={cfa95e6d-f669-4f9c-933e-a9f2eb0724ea}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy8
