@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {74ed2539-01ae-4bf9-a769-047b81aa2f91}]
@echo.

SET SHADOW_SET_ID={74ed2539-01ae-4bf9-a769-047b81aa2f91}
SET SHADOW_ID_1={0e0f07a7-63ed-4526-9187-534cfad542d0}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy28
