REM
REM called from vshadow via commandline e.g
REM 
REM    vshadow.exe -script=vss-setvar.cmd -exec=vss-exec.cmd e:
REM

REM Create a temporary name for the share, e.g. take the timestamp
REM 
set VSS_SHARE=vss_share_tra
echo #%TESTROOTDST%#

REM vss-setvar.cmd is generated by vshadow.exe
REM
call t_vss-setvar.cmd

REM create the temporary share
REM
%VSHADOW% -er=%shadow_id_1%,"%VSS_SHARE%"
%VSHADOW% -q
echo #%VSHADOW%#
net share

REM run the intended copy job 
REM
%LN% --copy \\%LH%\%VSS_SHARE%\1 %TESTROOTDST%
pause
