@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {c3f8ab92-d846-40ed-b62b-7e97a1edf23a}]
@echo.

SET SHADOW_SET_ID={c3f8ab92-d846-40ed-b62b-7e97a1edf23a}
SET SHADOW_ID_1={e9a0cf17-4b78-483e-a036-d484c2cd4e2b}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy16
