//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HardLink.rc
//
#define IDI_ICON1                       131
#define IDI_LINKSHLEXT_ICON_TAB         136
#define IDS_STRING_DrivePrefix          138
#define IDS_STRING_LanguageID           139
#define IDS_STRING_PropPageLinkType     140
#define IDS_STRING_PropPageRefCount     141
#define IDS_STRING_ProgressCreatingSmartMirror 142
#define IDS_STRING_PropPageCaption      143
#define IDS_STRING_Hardlink             144
#define IDS_STRING_Junction             145
#define IDS_STRING_LinkTypeSymlink      146
#define IDS_STRING_ErrDestSrcCircular   147
#define IDS_STRING_ProgressCreatingSmartCopy 148
#define IDS_STRING_MountPoint           149
#define IDS_STRING_ProgressCloning      150
#define IDS_STRING_ProgressCreatingDeLoreanCopy 151
#define IDS_STRING_ErrDirectoryNotEmpty 152
#define IDS_STRING_SymbolicLinkClone    153
#define IDS_STRING_HardlinkClone        154
#define IDS_STRING_ErrHardlinkFailed    155
#define IDS_STRING_ErrExplorerCanNotCreateMountpoint 156
#define IDS_STRING_ErrExplorerCanNotCreateHardlink 157
#define IDS_STRING_ErrExplorerCanNotCreateJunction 158
#define IDS_STRING_ErrExplorerCanNotCreateSymlink 159
#define IDS_STRING_ErrExplorerCanNotCreateHardlinkClone 160
#define IDS_STRING_ErrExplorerCanNotCreateSymlinkClone 161
#define IDS_STRING_ErrCreatingMountpoint 162
#define IDS_STRING_ErrCreatingHardlink  163
#define IDS_STRING_ErrCreatingJunction  164
#define IDS_STRING_ErrCreatingSymlink   165
#define IDS_STRING_ErrCreatingHardlinkClone 166
#define IDS_STRING_ErrCreatingSymlinkClone 167
#define IDS_STRING_Target               168
#define IDS_STRING_MountPointTarget     169
#define IDS_STRING_PropPageHardlinkEnum 170
#define IDS_STRING_PropPageEnumSiblings 171
#define IDS_STRING_ProgressEnumerating  172
#define IDS_STRING_ProgressCanceling    173
#define IDS_STRING_ExploreTarget        174
#define IDS_STRING_ProgressSmartMove    175
#define IDS_STRING_ErrExplorerCanNotCreateSmartCopy 176
#define IDS_STRING_ErrExplorerCanNotCreateSmartMirror 177
#define IDS_STRING_ErrExplorerCanNotCreateDeloreanCopy 178
#define IDS_STRING_ErrCreatingSmartCopy 179
#define IDS_STRING_ErrCreatingSmartMirror 180
#define IDS_STRING_ErrCreatingDeloreanCopy 181
#define IDS_STRING_BackupPrivilegesNotHeld 182
#define IDS_STRING_BackupFailed         183
#define IDS_STRING_ErrExplorerAutoRenAlreadyExists 184
#define IDS_STRING_eMenuHardlink        200
#define IDS_STRING_eMenuSymbolicLink    201
#define IDS_STRING_eMenuJunction        202
#define IDS_STRING_eMenuHardLinkClone   203
#define IDS_STRING_eMenuSymbolicLinkClone 204
#define IDS_STRING_eMenuReplaceJunction 205
#define IDS_STRING_eMenuSmartCopy       206
#define IDS_STRING_eMenuReplaceSymbolicLink 207
#define IDS_STRING_eMenuReplaceMountPoint 208
#define IDS_STRING_eMenuSmartMirror     209
#define IDS_STRING_eMenuDeloreanCopy    210
#define IDS_STRING_eMenuCreateMountPoint 211
#define IDS_STRING_eMenuDropeAs         212
#define IDS_STRING_eMenuDropHardlink    213
#define IDS_STRING_eMenuDropHardLinkClone 214
#define IDS_STRING_eMenuDropJunction    215
#define IDS_STRING_eMenuDropReplaceJunction 216
#define IDS_STRING_eMenuDropSmartCopy   217
#define IDS_STRING_eMenuDropSymbolicLink 218
#define IDS_STRING_eMenuDropReplaceSymbolicLink 219
#define IDS_STRING_eMenuDropReplaceMountPoint 220
#define IDS_STRING_eMenuDropSmartMirror 221
#define IDS_STRING_eMenuDropDeloreanCopy 222
#define IDS_STRING_eMenuHardlink1       223
#define IDS_STRING_eMenuSymbolicLink1   224
#define IDS_STRING_eMenuJunction1       225
#define IDS_STRING_eMenuHardLinkClone1  226
#define IDS_STRING_eMenuSymbolicLinkClone1 227
#define IDS_STRING_eMenuReplaceJunction1 228
#define IDS_STRING_eMenuSmartCopy1      229
#define IDS_STRING_eMenuReplaceSymbolicLink1 230
#define IDS_STRING_eMenuReplaceMountPoint1 231
#define IDS_STRING_eMenuSmartMirror1    232
#define IDS_STRING_eMenuDeloreanCopy1   233
#define IDS_STRING_eMenuCreateMountPoint1 234
#define IDS_STRING_eMenuDropeAs1        235
#define IDS_STRING_eMenuDropHardlink1   236
#define IDS_STRING_eMenuDropHardLinkClone1 237
#define IDS_STRING_eMenuDropJunction1   238
#define IDS_STRING_eMenuDropReplaceJunction1 239
#define IDS_STRING_eMenuDropSmartCopy1  240
#define IDS_STRING_eMenuDropSymbolicLink1 241
#define IDS_STRING_eMenuDropReplaceSymbolicLink1 242
#define IDS_STRING_eMenuDropReplaceMountPoint1 243
#define IDS_STRING_eMenuDropSmartMirror1 244
#define IDS_STRING_eMenuDropDeloreanCopy1 245
#define IDS_STRING_HelpText01           300
#define IDS_STRING_HelpText02           301
#define IDS_STRING_HelpText03           302
#define IDS_STRING_HelpText04           303
#define IDS_STRING_HelpText05           304
#define IDS_STRING_HelpText06           305
#define IDS_STRING_HelpText07           306
#define IDS_STRING_HelpText08           307
#define IDS_STRING_HelpText09           308
#define IDS_STRING_HelpText10           309
#define IDS_STRING_HelpText11           310
#define IDS_STRING_HelpText12           311
#define IDS_STRING_HelpText13           312
#define IDS_STRING_HelpText14           313
#define IDS_STRING_HelpText15           314
#define IDS_STRING_HelpText16           315
#define IDS_STRING_HelpText17           316
#define IDS_STRING_eTopMenuPickLinkSource 400
#define IDS_STRING_eTopMenuDeleteJunction 401
#define IDS_STRING_eTopMenuCancelLinkCreation 402
#define IDS_STRING_eTopMenuHardlink     403
#define IDS_STRING_eTopMenuJunction     404
#define IDS_STRING_eTopMenuSymbolicLink 405
#define IDS_STRING_eTopMenuTo           406
#define IDS_STRING_eTopMenuOf           407
#define IDS_STRING_eTopMenuReference    408
#define IDS_STRING_eTopMenuHardlinkClone 409
#define IDS_STRING_eTopMenuSymbolicLinkClone 410
#define IDS_STRING_eTopMenuReferenceHelpText 411
#define IDS_STRING_eTopMenuDeleteMountPoint 412
#define IDS_STRING_eTopMenuMountPoint   413
#define IDS_STRING_eTopMenuSmartCopy    414
#define IDS_STRING_eTopMenuOfOrderXP_1  415
#define IDS_STRING_eTopMenuOfOrderXP_2  416
#define IDS_STRING_eTopMenuOfOrderXP_3  417
#define IDS_STRING_eTopMenuOfOrderW7_1  418
#define IDS_STRING_eTopMenuOfOrderW7_2  419
#define IDS_STRING_eTopMenuOfOrderW7_3  420
#define IDS_STRING_eTopMenuOfOrderW7_4  421
#define IDS_STRING_eTopMenuOfOrderW7_5  422
#define IDS_STRING_eTopMenuOfOrderW7_6  423
#define IDS_STRING_eTopMenuOfOrderW7_7  424
#define IDS_STRING_eTopMenuOfOrderW7_8  425
#define IDS_STRING_eTopMenuOfOrderW7_9  426
#define IDC_PROPPAGE_LINKSHLEXT_FILENAME 1001
#define IDC_PROPPAGE_LINKSHLEXT_LINKTYPE 1002
#define IDC_PROPPAGE_LINKSHLEXT_REFTARGET 1003
#define IDC_PROPPAGE_LINKSHLEXT_HARDLINKENUM 1004
#define IDC_PROPPAGE_LINKSHLEXT_LINKTYPE_VALUE 1005
#define IDC_PROPPAGE_LINKSHLEXT_REFTARGET_VALUE 1006
#define IDC_PROPPAGE_LINKSHLEXT_HARDLINKS 1007
#define IDD_LINKSHLEXT_PROPPAGE         1008
#define IDC_EXPLORE_TARGET              1011
#define IDC_PROPPAGE_LINKSHLEXT_REFTARGET_ABSOLUT_VALUE 1017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
